name: example-ct-webpack-react-ts
on:
  workflow_dispatch:

jobs:

  test-default:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress tests
        uses: cypress-io/github-action@v7
        with:
          working-directory: examples/ct-webpack-react-ts
          component: true

  test-node:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22
          - 24
          - 26
    name: Cypress Cucumber on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress tests
        uses: cypress-io/github-action@v7
        with:
          working-directory: examples/ct-webpack-react-ts
          component: true
          command: npx cypress run --component
